import type { Metadata } from 'next';
import VelorBooking, { VelorInquiry, InquiryLink, BookingLink } from './VelorBooking';
import { addons, packages, sizes, parkingBenefit } from '../lib/velor-menu';
import './velor-refresh.css';
export const metadata: Metadata = { title: 'Velor Car Care | Vehicle care without the extra trip', description: 'Premium car care at participating Express garages. Exterior care from $39, interior refresh, complete care, fleet inquiries and corporate car care days in New Haven.' };
const faqs = [
  ['Where can I book service?', 'Start with 96 Orange Street Garage in New Haven. Service at other garages and lots depends on participation and availability; contact us about your location.'],
  ['What is included?', 'Compare the three packages above. Heavy buildup, stains, pet hair, extraction and restoration are outside routine care. Any additional work is quoted and approved before starting.'],
  ['How do keys and interior access work?', 'We arrange access before confirming interior service. Do not leave your vehicle unlocked or keys unattended. We verify the vehicle and space before work; any necessary vehicle movement must be agreed with you in advance.'],
  ['How long does service take?', 'Timing depends on vehicle size, condition, package and add-ons. Choose your service date and preferred Velor window. We confirm availability before accepting the appointment; submitting a request does not reserve a time.'],
  ['Are parking charges included?', parkingBenefit],
  ['How do monthly plans work?', 'Choose a monthly plan in the same booking form used for one-time care. Each plan covers one registered vehicle and two scheduled visits per month, subject to availability. Final rollover, rescheduling, cancellation and visit-expiry terms are provided before payment.'],
  ['Can I reschedule or report something missed?', 'Call 203-941-0954 as soon as possible to request a schedule change or report a service concern. Include your appointment details and what needs attention. Rescheduling terms are provided with confirmation.'],
  ['How are photos and screens handled?', 'Before-and-after photos are kept private as a service record, not used for marketing without permission. Screens receive gentle care with a dedicated display microfiber cloth, following vehicle instructions. No steam service or added fragrance unless you request fragrance.'],
];
const propertyFaqs = [
  ['How much involvement is required from property staff?', 'None in the day-to-day service. Velor handles customer communication, scheduling, payments and service questions directly.'],
  ['Does the property have to manage bookings or payments?', 'No. Residents, employees or guests book directly with Velor. Velor handles confirmations, payments and customer support so the property team does not become the service desk.'],
  ['What does it cost the property?', 'A standard resident- or employee-paid Velor program can be structured with no direct service cost to the property. Sponsored employee or resident programs are optional and priced separately only if the property chooses them.'],
  ['Does the property need to manage the service onsite?', 'No. Velor manages the service directly with the customer. Property staff do not need to coordinate appointments, handle payments or supervise the service.'],
  ['Can we test it before making it a regular amenity?', 'Yes. A Velor Day can be used as a simple pilot to measure interest and confirm that the operating setup works for the property before expanding the program.'],
  ['What does the property receive?', 'A convenient vehicle-care amenity for residents, employees or guests without adding a new daily task for property staff. Velor manages the customer experience from booking through completion.'],
];
export default function VelorPage() { return <main className="vr-page">
  <section className="vr-hero vr-wrap"><span className="vr-kicker">EXPRESS / VELOR CAR CARE</span><h1>Vehicle care<br/>without the<br/><em>extra trip.</em></h1><p className="vr-lead">Premium care, right where you park. Save time while Velor cleans your vehicle with water-conscious, environmentally responsible methods.</p><p className="vr-eco-line">Water-conscious. Environmentally responsible. Convenient.</p><div className="vr-actions"><a className="vr-button" href="#book-velor">Book your service</a><a className="vr-button vr-outline" href="#menu">Explore services</a></div></section>
  <div className="vr-wrap">
  <section className="vr-section"><span className="vr-kicker">THE VELOR EXPERIENCE</span><h2>Park. Plan. Return to clean.</h2><div className="vr-grid">{[['01 / Book','Choose one-time care or a monthly plan, then tell us your vehicle, space, service date and preferred Velor window.'],['02 / Care','We verify the vehicle, arrange access and document its condition. Extra work always needs your approval.'],['03 / Complete','Receive completion confirmation and a record of the work, with private before-and-after photos. Something missed? Contact us.']].map(([title,text])=><article className="vr-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="vr-section" id="menu"><span className="vr-kicker">ONE-TIME CARE</span><h2>We clean your car while you park.<br/>Without going out of your way.</h2><p className="vr-section-lead">Save the extra trip and spend your time on something else. Velor delivers convenient, premium car care with water-conscious, environmentally responsible methods while your vehicle is already parked.</p><div className="vr-grid">{packages.map(p=><article className="vr-card" key={p.name}><h3>{p.name}</h3><p>{p.description}</p></article>)}</div><div className="vr-table"><table><caption>One-time service prices</caption><thead><tr><th scope="col">Vehicle size</th>{packages.map(p=><th scope="col" key={p.name}>{p.name}</th>)}</tr></thead><tbody>{sizes.map(s=><tr key={s.id}><th scope="row">{s.name}<small>{s.detail}</small></th>{s.prices.map((p,i)=><td key={i}>${p}</td>)}</tr>)}<tr><th scope="row">Oversized, commercial or specialty</th><td>Quote</td><td>Quote</td><td>Quote</td></tr></tbody></table></div><p>Heavy buildup, stains, pet hair, extraction and restoration are additional work. We assess suitability before waterless exterior care. Screens are cleaned gently with a dedicated display microfiber cloth, following vehicle instructions. No steam cleaning. No added fragrance unless requested.</p></section>
  <section className="vr-section"><span className="vr-kicker">MAKE IT YOURS</span><h2>A little extra attention.</h2><p>Available with Interior Refresh or Complete Care. Scope and suitability are confirmed before work.</p><div className="vr-grid vr-grid-four">{addons.map(a=><article className="vr-card" key={a.name}><span className="vr-price">${a.price}</span><h3>{a.name}</h3><p>{a.scope}</p></article>)}</div><p>Heavy pet hair, deep extraction, odor treatment, pickup-bed cleaning and commercial work require a separate assessment and quote. Availability depends on suitable methods, equipment and service capability.</p></section>
  <section className="vr-section"><span className="vr-kicker">A REGULAR RESET</span><h2>Two visits. Every month.</h2><p>Monthly plans for one registered vehicle, with two scheduled visits subject to availability. Select your plan and service window in the same booking flow as one-time care.</p><div className="vr-table"><table><caption>Monthly plan prices — two visits per month</caption><thead><tr><th>Vehicle size</th><th>Exterior Care</th><th>Complete Care</th></tr></thead><tbody>{sizes.map(s=><tr key={s.id}><th scope="row">{s.name}</th>{s.plans.map((p,i)=><td key={i}>${p}<small>per month</small></td>)}</tr>)}</tbody></table></div><p>Final rollover, rescheduling, cancellation and expiry terms are shown before payment. Monthly service is available only when the selected Velor window has capacity.</p><BookingLink mode="monthly">Choose a monthly plan</BookingLink></section>
  <section className="vr-section" id="book-velor"><VelorBooking/></section>
  <section className="vr-section"><span className="vr-kicker">FOR YOUR ORGANIZATION</span><h2>Care beyond the daily drive.</h2><div className="vr-grid vr-grid-two"><article className="vr-card"><h3>Fleet &amp; Business Vehicle Care</h3><ul><li>Local business and service vehicles</li><li>Delivery and transportation fleets</li><li>Rideshare vehicles</li><li>Rideshare and shared bicycles</li><li>Municipal and state passenger vehicles, SUVs and light-duty trucks</li></ul><p>Scheduled exterior, interior or combined care. Quotes reflect vehicle type, quantity, condition, frequency and location. Bicycles have their own component-appropriate scope and pricing. Government inquiries are subject to purchasing and vendor requirements.</p><InquiryLink interest="Fleet & Business Vehicle Care">Request a Fleet Quote</InquiryLink></article><article className="vr-card"><h3>Corporate Clean Car Day</h3><p>Give your employees a clean car while they work.</p><p>Arrange a scheduled care day at your workplace or participating garage. Sponsor a service as an appreciation gift, contribute part of the cost or arrange individual service vouchers.</p><p>We agree on packages, vehicle count, schedule and company budget in advance. Employees reserve available appointments; personal upgrades require their approval.</p><InquiryLink interest="Corporate Clean Car Day">Request a Corporate Clean Car Day</InquiryLink></article></div></section>
  <section className="vr-section"><h2>Good to know.</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  <section className="vr-section"><span className="vr-kicker">PROPERTY PARTNERSHIPS</span><h2>A clean-car amenity.<br/>No work for your property team.</h2><p>Velor brings scheduled vehicle care to workplaces, residential properties, garages and lots while handling the customer experience directly. No property staff involvement, no property-side booking or payment handling, and a standard customer-paid program can be structured with no direct service cost to the property.</p>{propertyFaqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<div className="vr-actions"><InquiryLink interest="Bring Velor to Your Property">Bring Velor to Your Property</InquiryLink></div></section>
  <section className="vr-section"><VelorInquiry/></section><p className="vr-support">Questions or something missed? <a href="tel:2039410954">Call 203-941-0954</a>.</p>
  </div></main>; }
